### ISSUE TITLE
Driving logs only as AM

### ISSUE THREAD

**Issue by frozenworks** [Okiesmokie/fitbitlog#1]
When the app posts the driving activity to fit bit.com it only logs it as AM only. For example a driving log starting at 3:00 PM with a duration of 10 minutes is logged as 3:00AM on fit bit.com

**Comment by Okiesmokie** [comment]
This was fixed in commit https://github.com/Okiesmokie/fitbitlog/commit/dc676ddd719a8df9b8571216ccab6e1abd0d904c
